### ISSUE TITLE
Mismatch between the played episodes count & actually played episodes

### ISSUE THREAD

**Issue by traxys** [jeff-hughes/shellcaster#10]
I'm sorry I have no more information on how I manage to create that issue, but I had a discrepancy between the played episodes count and the list of played episodes, the count was 0 but I had one unread episode. When I marked that episode as unplayed it underflowed the count

I have not managed to replicate that issue tough

**Comment by jeff-hughes** [comment]
It's not surprising that you ran into this -- the logic for counting played episodes is a bit fragile at the moment, I need to come up with a better way to manage it in general. At any rate, I'll see if I can replicate this issue. But even if not, I'll probably be ripping out that code and replacing it anyway. Thanks for reporting it!

**Comment by jeff-hughes** [comment]
I haven't been able to replicate this issue, but I have also revamped the code that tracks the count of played episodes, so this may correct the error. This code will be included in the next release. I'm going to consider this resolved for now, but feel free to reopen the issue if you still come across it.
