### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by a-kenji** [jeff-hughes/shellcaster#16]
Hello!
I am enjoying your project.
Do you have a feature list somewhere
of things you are still wanting to implement?

**Comment by jeff-hughes** [comment]
Hi there! Glad you're enjoying it.

I have resisted posting any sort of official "roadmap" of features (mostly in case I change my mind and don't want people to hold me accountable :) ) but here are a few things that I will likely be including:

1. A help window to show the keybindings
2. After syncing podcasts, a popup window listing the new episodes and the ability to select which ones to download. Along with this, options in the config file to "always" or "never" download new episodes, or "ask" which add the popup window
3. An estimated time remaining for files being downloaded
4. Possibly a search function for searching the Apple Podcasts (or some similar) database

**Comment by a-kenji** [comment]
Yeah, that makes sense.
Thanks for sharing! Sounds good.
