### ISSUE TITLE
Help window.

### ISSUE THREAD

**Issue by a-kenji** [jeff-hughes/shellcaster#18]
Add a help window which can show current keybindings.

Maybe also with a search functionality?

Edit: I will try to make a simple help page.

**Comment by jeff-hughes** [comment]
Thanks for adding this -- I certainly welcome contributions (including your PR; I've seen it, just haven't had a chance to get to it yet!). However, just so you know, I already have about half an implementation of a help window set up. I am wanting to set up a more general "popup window" system that will integrate the welcome window (the window shown when you first start the program and have no podcasts), as well as a download menu that happens after syncing podcasts. These will all have the same general "popup" structure as the help menu, so I want something to accommodate all of these in a reasonable way.

However, I had not considered the idea of a search functionality in the help window. That sounds interesting! Perhaps it would be easier for you to contribute on that, once I have the help window functionality set up? Like I said, I welcome the contribution, I just don't want to end up duplicating work.

**Comment by a-kenji** [comment]
Awesome! Yes I started a bit with the help window. But I mostly replicated the welcome window. A popup solution sounds good. 

I'll  open tickets for general search functionality. Maybe it makes sense in the help menu too. 

Also showing keybindings and what is assigned for example to the play command could be helpful.

**Comment by jeff-hughes** [comment]
Forgot to tag this in the commit, but v1.1.0 now has a help window accessible by pressing "?".
