### ISSUE TITLE
Add compiling instructions section to readme

### ISSUE THREAD

**Issue by thunderBiscuit** [jeff-hughes/shellcaster#2]
Just to make it clear on how to compile for personal use. Something like this maybe?

## Compile Shellcaster Yourself
You can build the binaries for yourself by going through the following steps:

```sh
git clone https://github.com/jeff-hughes/shellcaster.git
cd shellcaster
cargo build --release
cd ./target/release/bin/
cp ./shellcaster /usr/local/bin/    # for Linux and MacOS
```

**Comment by jeff-hughes** [comment]
Good call! I've added some instructions to the readme.
