### ISSUE TITLE
Enabling Github Pages

### ISSUE THREAD

**Issue by thunderbiscuit** [jeff-hughes/shellcaster#26]
Just found out today that you can enable Github pages without anything else and it will render your readme in it's own website.

Nice little touch. People can bookmark the site if they use shellcaster and wish to reference the hot keys and all. Github also supports about 10 themes off the bat if you want to spice it up, or you can add a `_config.yaml` file and actually reference any third-party Jekyll theme if you prefer something else.

Just wanted to bring it to your attention in case you didn't know!

**Comment by jeff-hughes** [comment]
Cool, that's good to know! I took a quick look -- all the default themes it provides somehow look like Powerpoint 97 backgrounds to me, haha, but maybe I'll look into some sort of custom theme. Thanks for letting me know!

**Comment by thunderbiscuit** [comment]
Cheers. Yeah those were my exact thoughts. The default themes are retro but not in a good way... The simplest and cleanest option is to have no theme at all, which will render the readme pretty much as rendered on the repo landing page but on its own page.

This issue is ready to be closed.
