### ISSUE TITLE
Add a rust-toolchain / rust-toolchain.toml file.

### ISSUE THREAD

**Issue by a-kenji** [jeff-hughes/shellcaster#31]
I think it would be valuable to add a rust-toolchain file,
if it is powerful enough.
That way the rustfmt versions should also be in sync.

[toolchain]
channel = "Strings"
components = [ "Strings" ]
targets = [ "Strings" ]

https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

**Comment by jeff-hughes** [comment]
Thanks for this. It's definitely a good idea, and if we can figure out a way to set it up, that would be great. My reading of this, though, is that the toolchain is specified for the project, not for each particular component, and I definitely don't want to pin the project as a whole to the nightly channel if I can help it. Based on what it's saying, it sounds like I could specify multiple toolchains, but it's not entirely clear how to specify rustfmt only for one of those chains, or if that would even do what I want...

I don't know. I'll definitely keep looking into it -- thanks for putting it on my radar!

**Comment by a-kenji** [comment]
No problem!
I looked into it more and sadly it doesn't look powerful enough yet, to pull clippy or rustfmt from different versions sadly.
