### ISSUE TITLE
Trying to scroll on an empty list panics

### ISSUE THREAD

**Issue by jeff-hughes** [jeff-hughes/shellcaster#4]
See for details: https://github.com/jeff-hughes/shellcaster/issues/3#issuecomment-622223611

**Comment by thunderBiscuit** [comment]
Ok we're getting somewhere! You are right it has to do with the scrolling. So I can fire up the app and it just stays there, like a full screen of empty stuff, but I have about half of it highlighted. If I use the right arrow that "highlighted" portion then becomes the whole screen. If I try to use the down arrow however, I get this error:

```rust
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/ui.rs:473:27 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jeff-hughes** [comment]
Okay, it sounds odd that half the screen is highlighted -- it should just be one line that is highlighted. Given that, it sounds like perhaps it's an issue with the underlying ncurses library that the app relies on -- most of the rest is Rust-based, but curses/ncurses is a C library, and there are some cross-platform differences.

Can you try this code out and see if that fixes it? https://github.com/ihalila/pancurses/issues/1#issuecomment-219354892

(On a side note, the `RUST_BACKTRACE=1` doesn't really work properly because ncurses hijacks the terminal to display things. Normally the backtrace will give you a nice run-through of the full stack when the program panicked. Only way I've found so far to get around that is to pipe stderr to a file: `RUST_BACKTRACE=1 cargo run 2> error.log`. But anyway, not sure that will be very useful here...and I know at least part of the problem is just trying to subtract from a zero-length list.)

**Comment by jeff-hughes** [comment]
Yeah, so currently when you first start the app with an empty database, it just looks like that. There's an empty menu list, and it highlights the first element in that zero-element list, so it just looks...empty. But it's successfully running. If you press "a" you can add a new feed and get the ball rolling so it's no longer empty.

But yes, I'll add it to my todo list: There needs to be a sort of "welcome screen" to show people that it's working properly and give some hints about the keyboard shortcuts to get things rolling. For now....you just have to rely on the Github readme :)

**Comment by jeff-hughes** [comment]
(Also, as a side note, I've found the backtrace thing doesn't quite work properly because the program is using ncurses and thus it hijacks the terminal output. The workaround I've found at the moment is just to pipe stderr to a file, so the backtrace ends up in there. Something like so: `RUST_BACKTRACE=1 cargo run 2> error.log` )
