### ISSUE TITLE
Error building package

### ISSUE THREAD

**Issue by ktpx** [jeff-hughes/shellcaster#41]
Trying to build this, i get this error

   Compiling unicode-normalization v0.1.17
error: generic parameters may not be used in const operations
   --> /data/home/.cargo/registry/src/github.com-1ecc6299db9ec823/jetscii-0.4.4/src/simd.rs:109:13
    |
109 |             T::CONTROL_BYTE,
    |             ^^^^^^^^^^^^^^^ cannot perform const operation using `T`
    |
    = note: type parameters may not be used in const expressions

error: generic parameters may not be used in const operations
   --> /data/home/.cargo/registry/src/github.com-1ecc6299db9ec823/jetscii-0.4.4/src/simd.rs:148:13
    |
148 |             T::CONTROL_BYTE,
    |             ^^^^^^^^^^^^^^^ cannot perform const operation using `T`
    |
    = note: type parameters may not be used in const expressions

error: aborting due to 2 previous errors

**Comment by jeff-hughes** [comment]
Thanks for flagging this, yeah this is something that cropped up recently, I think with the update to rustc 1.54.0. Apparently this particular issue was not backwards compatible. Updating one of the dependencies fixes the issue, so I'm working on a quick patch release to do that. Should be up shortly!

**Comment by ktpx** [comment]
Thanks for the quick fix :D
