### ISSUE TITLE
ignores config?

### ISSUE THREAD

**Issue by ktpx** [jeff-hughes/shellcaster#42]
Hi,

Is it not possible change the background color? I need white on black text, but 
setting that in the config does nothing. 

Im trying to reverse the colors, as i cant read black background on white foreground very well.

Thanks

**Comment by jeff-hughes** [comment]
Hi @ktpx,

Could you paste the contents of your config file, please? It should be possible to change the colours, but if any option in the config is not set properly (e.g., a typo), it will fall back on the defaults. Of course, also possible there's a bug :)

**Comment by ktpx** [comment]
`download_path = "/media/Podcasts"
[colors]
normal_foreground = "black"
normal_background = "white"
error_foreground = "black"
error_background = "white"

**Comment by ktpx** [comment]
Yeah, must be a terminal problem...nevermind, closing it.

**Comment by jeff-hughes** [comment]
Ahh yes, the named colours like "white", "black", "red", etc. refer to the 8-colour ANSI standard colours, and thus will use whatever colours those are set to in your terminal. (For example, "white" in my terminal is actually set to a light grey colour.) Specifying the colours directly with hex codes or "rgb(_, _, _)" in the config file should work--provided your terminal has wider colour support, of course.

I will see if I can make that a bit clearer in the documentation to hopefully avoid some confusion. Anyway, glad you got it working!

**Comment by ktpx** [comment]
Thanks for the tip.

yeah, the color wasnt really white as you said, was greyish,  Thanks for the tip, will use the RGB codes (im using e-ink screen, so i just want plain white :D )

Ktp
