### ISSUE TITLE
`Error sending download request.` when downloading episodes from specific podcast

### ISSUE THREAD

**Issue by Elcoid** [jeff-hughes/shellcaster#63]
Hello, I have the problem described in the title only with a specific podcast: https://rss.art19.com/sean-carrolls-mindscape

I'm able to sync the feed and display all the episodes, but not download any episode. `Error sending download request.` gets printed in red for a second or two at the bottom of the screen when I try, then `Downloading 1 episode...` gets printed instead and stays forever (or at least I'm assuming it's forever, I didn't verify).

**Comment by dougli1sqrd** [comment]
I think this is the same problem as the issue I made yesterday: https://github.com/jeff-hughes/shellcaster/issues/62

I think shellcaster (and VLC for that matter) isn't following redirects

**Comment by Elcoid** [comment]
You're right, the symptoms I saw are the same as those described in your issue. We would just need to check if the podcast I linked above uses redirects. If so, I would close this issue.

**Comment by Elcoid** [comment]
Yup, I confirm this is because Shellcaster gets a 302 and doesn't know what to do with it. So this issue is the same as #62.
