### ISSUE TITLE
Selecting and playing a new podcast doesn't stop the currently running one

### ISSUE THREAD

**Issue by thunderbiscuit** [jeff-hughes/shellcaster#8]
You can even start the same podcast a few times in a row a few seconds apart for a sweet "round" style podcast experience.

**Comment by jeff-hughes** [comment]
Yes, this isn't a bug per se. The app just executes a command and lets the media player assume complete control over the file. So if you want the currently playing file to stop, you need to go to whatever media player you're using and stop it.

That said, I am realizing that if you use a media player with no GUI at all, it's just going to spawn a new process in the background to play the file and you may be stuck with no media controls at all. You might have to manually kill the process. So I'll have to at least add a warning for people to make sure they are executing a command that launches a GUI!
